# -*- coding: utf-8 -*-
"""Fill all 11 languages with full subpage translations (no EN fallback for page keys)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALES = ROOT / "js" / "locales.js"

# Full packs for non-EN/TR languages — same keys as PAGES_TR + SHARED_TR
DE = {
    "common.cta.meeting": "Gespräch anfragen",
    "common.cta.project": "Projektgespräch vereinbaren",
    "common.cta.back_services": "Zurück zu den Leistungen",
    "common.cta.send": "Anfrage senden",
    "common.cta.view_guides": "Leitfäden ansehen",
    "common.contact.h2": "Lassen Sie uns Ihr Projekt gemeinsam bewerten",
    "common.contact.p": "Vereinbaren Sie ein kurzes technisches Gespräch zu Scope, Zeitplan und nächsten Schritten.",
    "common.contact.name": "Vollständiger Name",
    "common.contact.email": "E-Mail",
    "common.contact.message": "Kurze Projektbeschreibung",
    "common.contact.success": "Vielen Dank. Wir haben Ihre Anfrage erhalten und melden uns in Kürze.",
    "common.proof": "Ausgewählte Referenzen",
    "common.detail": "Im Detail",
    "common.process": "Prozess",
    "common.more": "Weiter",
    "urunler.title": "SoftenWise | Produkte",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps und BLOC — das SoftenWise-Produktportfolio.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "Produkte",
    "urunler.lead": 'Von der Klinik bis zu Karten und Mobile: unsere Produkte finden Sie hier. Für Individualsoftware oder Integration siehe unsere <a href="index.html#solutions">Leistungen</a>.',
    "urunler.cta1": "Produkte ansehen",
    "urunler.cta2": "Gespräch anfragen",
    "urunler.featured": "Highlights",
    "urunler.jump": "Zu Produktdetails springen",
    "urunler.clinic.desc": "Klinikprozesse von Termin bis Finanzen in einem Panel steuern.",
    "urunler.clinic.cta": "Technische Details prüfen",
    "urunler.otomini.desc": "Gebrauchtwagenbewertung, Inspektion und Galerie-Vitrine.",
    "urunler.otomini.cta": "Technische Details prüfen",
    "urunler.maps.desc": "Unternehmens-GIS für den Außendienst: Karten, Zonen, Routing und REST-API.",
    "urunler.maps.cta": "Überblick und Links",
    "urunler.bloc.badge": "Mobile App",
    "urunler.bloc.desc": "Community- und Social-Feed-orientierte iOS-/Android-App.",
    "urunler.bloc.cta": "App-Überblick",
    "urunler.kicker.portfolio": "Portfolio",
    "urunler.kicker.eco": "SoftenWise-Ökosystem",
    "urunler.visit": "Zur Produktwebsite",
    "urunler.clinic.lead": "Ein Web-Panel, das Klinikprozesse von Termin und Patientenverwaltung bis Finanzen und Reporting zentralisiert.",
    "urunler.clinic.b1": "<strong>11 Sprachen</strong> und länderübergreifende Infrastruktur; Filialsichtbarkeit",
    "urunler.clinic.b2": "Patienten- und Besuchs-, Termin-, Finanz- und Reportingmodule",
    "urunler.clinic.b3": "Rollenbasierter Zugriff und <strong>Audit-Log</strong> für Nachvollziehbarkeit",
    "urunler.clinic.b4": "Webbasiertes Panel; SaaS- oder Kunden-Cloud-Optionen",
    "urunler.clinic.b5": "<strong>15 Tage kostenlose Testphase</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Für Polikliniken, private Medizinzentren und Mehrfilialstrukturen",
    "urunler.otomini.lead": "Vertrauensorientierter Gebrauchtwagenhandel: sofortige digitale Bewertung, transparente Inspektion und professionelle Galerie.",
    "urunler.otomini.b1": "<strong>Intelligente Bewertung:</strong> Vorwert in Sekunden aus Marke, Modell und Ausstattung",
    "urunler.otomini.b2": "<strong>Transparente Inspektion:</strong> Schadens- und Historienzusammenfassung",
    "urunler.otomini.b3": "<strong>Inseratsverwaltung:</strong> galerieorientierte Präsentation in der Otomini-Vitrine",
    "urunler.otomini.b4": "Für Gebrauchtwagenhändler, Händlernetze und Handelsteams",
    "urunler.otomini.b5": "Eigenständige Produktmarke mit SoftenWise-Engineering",
    "urunler.maps.lead": "Ein unternehmensweites <strong>GIS</strong>-Ökosystem zur Steuerung von Außeneinsätzen: Karten, Zonen, Routing, Reporting und REST-API.",
    "urunler.maps.b1": "<strong>Ein Panel:</strong> Karte, Layer-Baum, Zeichenwerkzeuge; Live-Fokus per Adresse / Koordinaten",
    "urunler.maps.b2": "Sichere und gesperrte Zonen (Polygone); versionierte Änderungshistorie",
    "urunler.maps.b3": "Geocode, Routing, Distanzmatrix; GeoJSON / KML und <strong>REST-API</strong>-Integration",
    "urunler.maps.b4": "XYZ-Kacheln, Nominatim, WMS / WMTS; Google Maps Platform oder On-Prem-Kartendienste",
    "urunler.maps.b5": "Multi-Tenant-Architektur, rollenbasierter Zugriff; OpenAPI / Redoc-Dokumentation",
    "urunler.maps.b6": "Für Außendienst, Logistik und Gebietsplanung",
    "urunler.bloc.lead": "Community- und Social-Feed-orientierte <strong>iOS- und Android</strong>-App — Teilen, Entdecken und Interaktion in einem Produkt.",
    "urunler.bloc.b1": "Verteilung über App Store und Google Play",
    "urunler.bloc.b2": "Oberfläche für Social Feed und Community-Interaktion",
    "urunler.bloc.b3": "Mit SoftenWise-Engineering-Standards entwickelt",
    "urunler.bloc.b4": "Store-first Produktlebenszyklus",
    "urunler.bloc.b5": "Native Erfahrung für iOS und Android",
    "svc.custom.brand": "Softwareentwicklung",
    "svc.custom.h1": "Individuelle Softwareentwicklung",
    "svc.custom.lead": "Wir bauen modulare Plattformen jenseits von Standardpaketen — Prozesse vereinfachen und mit Ihrem Geschäft skalieren.",
    "svc.custom.title": "SoftenWise | Individuelle Softwareentwicklung",
    "svc.mobile.brand": "Mobile Entwicklung",
    "svc.mobile.h1": "Mobile Entwicklung",
    "svc.mobile.lead": "Produktorientierte native und hybride Apps für iOS und Android — vom Store-Release bis zum Live-Monitoring.",
    "svc.mobile.title": "SoftenWise | Mobile Entwicklung",
    "svc.integ.brand": "Integration & Automatisierung",
    "svc.integ.h1": "Integration & Automatisierung",
    "svc.integ.lead": "Wir verbinden isolierte Systeme und automatisieren Datenflüsse, um manuelle Fehler zu reduzieren und Teams freizusetzen.",
    "svc.integ.title": "SoftenWise | Integration & Automatisierung",
    "svc.sec.brand": "Sicherheit & Audit",
    "svc.sec.h1": "Sicherheit & Audit",
    "svc.sec.lead": "Wir stärken Ihre Systeme gegen Cyberbedrohungen und begleiten Compliance sowie technische Audits.",
    "svc.sec.title": "SoftenWise | Sicherheit & Audit",
    "svc.consult.brand": "Technische Beratung",
    "svc.consult.h1": "Technische Beratung",
    "svc.consult.lead": "Klare Beratung zu Architektur, Refactoring und Skalierung — ohne unnötige technische Schulden.",
    "svc.consult.title": "SoftenWise | Technische Beratung",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "Engineering-Disziplin gemeinsam stärken",
    "academy.lead": "Die SoftenWise Academy stellt Engineering-Disziplin und skalierbare Systemarchitektur in den Mittelpunkt — nicht nur Code.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "SoftenWise Karriere",
    "career.h1": "Echte Produkte, hoher Traffic, messbares Wachstum",
    "career.lead": "Bei SoftenWise übernehmen Sie Verantwortung in Architekturentscheidungen für Hochlastsysteme und lösen Performance- und Skalierungsfragen in realen Projekten.",
    "career.title": "SoftenWise | Karriere",
    "partner.brand": "Venture-Partnerschaft",
    "partner.h1": "Ideen mit unserer technischen Kapazität wachsen lassen",
    "partner.lead": "Wir verwandeln vielversprechende Visionen durch technische Validierung, MVP-Lieferung und Wachstumsstrategie in tragfähige Modelle.",
    "partner.title": "SoftenWise | Venture-Partnerschaft",
    "resources.brand": "Ressourcencenter",
    "resources.h1": "Klare Leitfäden für Software-Entscheidungen",
    "resources.lead": "Inhalte zu realen Entscheiderfragen — Auswahl, Kosten und Prozesse klarer machen.",
    "resources.title": "SoftenWise | Ressourcen",
    "guide.firm.brand": "Leitfaden",
    "guide.firm.h1": "Wie wählt man einen Softwarepartner?",
    "guide.firm.lead": "Der richtige Technologiepartner prägt den Projekterfolg. Wir haben kritische Prüfpunkte von Angebot bis Technikqualität zusammengestellt.",
    "guide.firm.title": "SoftenWise | Softwarepartner wählen",
    "guide.cost.brand": "Kostenleitfaden",
    "guide.cost.h1": "Wie berechnet sich der Preis individueller Software?",
    "guide.cost.lead": "Ein praktischer Rahmen für Scope-Analyse, Budgetplanung und transparente Umsetzung.",
    "guide.cost.title": "SoftenWise | Kosten individueller Software",
    "guide.mobile.brand": "Mobile Leitfaden",
    "guide.mobile.h1": "Prozess der mobilen App-Entwicklung",
    "guide.mobile.lead": "Erfolgreiche Mobile-Produkte entstehen durch Discovery, Tests und Release-Disziplin — nicht nur durch Code.",
    "guide.mobile.title": "SoftenWise | Mobile App-Prozess",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — Seite nicht gefunden",
    "err404.lead": "Diese Adresse existiert möglicherweise nicht mehr oder wurde falsch eingegeben. Weiter über Startseite, Leistungen oder Ressourcen.",
    "err404.title": "SoftenWise | Seite nicht gefunden",
    "err404.home": "Zur Startseite",
}

FR = {
    "common.cta.meeting": "Demander un entretien",
    "common.cta.project": "Planifier une discussion projet",
    "common.cta.back_services": "Retour aux services",
    "common.cta.send": "Envoyer la demande",
    "common.cta.view_guides": "Voir les guides",
    "common.contact.h2": "Évaluons votre projet ensemble",
    "common.contact.p": "Planifiez un court échange technique pour clarifier périmètre, calendrier et prochaines étapes.",
    "common.contact.name": "Nom complet",
    "common.contact.email": "E-mail",
    "common.contact.message": "Bref aperçu de votre projet",
    "common.contact.success": "Merci. Nous avons bien reçu votre demande et vous répondrons rapidement.",
    "common.proof": "Références sélectionnées",
    "common.detail": "En détail",
    "common.process": "Processus",
    "common.more": "Suite",
    "urunler.title": "SoftenWise | Produits",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps et BLOC — le portefeuille produits SoftenWise.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "Produits",
    "urunler.lead": 'De la clinique aux cartes et au mobile : nos produits sont réunis ici. Pour un logiciel sur mesure ou une intégration, consultez nos <a href="index.html#solutions">services</a>.',
    "urunler.cta1": "Voir les produits",
    "urunler.cta2": "Demander un entretien",
    "urunler.featured": "À la une",
    "urunler.jump": "Aller aux détails produit",
    "urunler.clinic.desc": "Gérez les processus cliniques du rendez-vous à la finance sur un seul panneau.",
    "urunler.clinic.cta": "Voir les détails techniques",
    "urunler.otomini.desc": "Estimation, expertise et vitrine pour véhicules d’occasion.",
    "urunler.otomini.cta": "Voir les détails techniques",
    "urunler.maps.desc": "SIG d’entreprise pour le terrain : cartes, zones, itinéraires et API REST.",
    "urunler.maps.cta": "Résumé et liens",
    "urunler.bloc.badge": "Application mobile",
    "urunler.bloc.desc": "Application iOS / Android orientée communauté et flux social.",
    "urunler.bloc.cta": "Aperçu de l’application",
    "urunler.kicker.portfolio": "Portefeuille",
    "urunler.kicker.eco": "Écosystème SoftenWise",
    "urunler.visit": "Aller sur le site produit",
    "urunler.clinic.lead": "Une console web qui centralise les processus cliniques, du rendez-vous et du suivi patient à la finance et au reporting.",
    "urunler.clinic.b1": "<strong>11 langues</strong> et infrastructure multi-pays ; visibilité par site",
    "urunler.clinic.b2": "Modules patient et visite, rendez-vous, finance et reporting",
    "urunler.clinic.b3": "Accès par rôles et <strong>journal d’audit</strong> pour la traçabilité",
    "urunler.clinic.b4": "Console web ; options SaaS ou cloud client",
    "urunler.clinic.b5": "<strong>Essai gratuit de 15 jours</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Pour polycliniques, centres médicaux privés et organisations multi-sites",
    "urunler.otomini.lead": "Commerce de véhicules d’occasion centré sur la confiance : estimation digitale instantanée, expertise transparente et vitrine professionnelle.",
    "urunler.otomini.b1": "<strong>Estimation intelligente :</strong> valeur préliminaire en secondes à partir de la marque, du modèle et des options",
    "urunler.otomini.b2": "<strong>Expertise transparente :</strong> synthèse des dommages et de l’historique",
    "urunler.otomini.b3": "<strong>Gestion des annonces :</strong> présentation orientée galerie sur la vitrine Otomini",
    "urunler.otomini.b4": "Pour concessions, réseaux de distributeurs et équipes d’achat-vente",
    "urunler.otomini.b5": "Marque produit indépendante conçue par SoftenWise",
    "urunler.maps.lead": "Écosystème <strong>SIG</strong> d’entreprise pour suivre les opérations de terrain depuis un seul panneau : cartes, zones, itinéraires, reporting et API REST.",
    "urunler.maps.b1": "<strong>Panneau unique :</strong> carte, arbre de couches, outils de dessin ; focus live par adresse / coordonnées",
    "urunler.maps.b2": "Zones sûres et interdites (polygones) ; historique versionné",
    "urunler.maps.b3": "Géocodage, itinéraire, matrice de distance ; GeoJSON / KML et intégration <strong>API REST</strong>",
    "urunler.maps.b4": "Tuiles XYZ, Nominatim, WMS / WMTS ; Google Maps Platform ou services cartographiques internes",
    "urunler.maps.b5": "Architecture multi-locataires, accès par rôles ; documentation OpenAPI / Redoc",
    "urunler.maps.b6": "Conçu pour le terrain, la logistique et la planification territoriale",
    "urunler.bloc.lead": "Application mobile <strong>iOS et Android</strong> orientée communauté et flux social — partage, découverte et interaction dans un seul produit.",
    "urunler.bloc.b1": "Distribution via App Store et Google Play",
    "urunler.bloc.b2": "Interface adaptée au flux social et à l’interaction communautaire",
    "urunler.bloc.b3": "Développée selon les standards d’ingénierie SoftenWise",
    "urunler.bloc.b4": "Cycle de vie produit orienté stores",
    "urunler.bloc.b5": "Expérience native pour iOS et Android",
    "svc.custom.brand": "Développement logiciel",
    "svc.custom.h1": "Développement logiciel sur mesure",
    "svc.custom.lead": "Nous construisons des plateformes modulaires au-delà des progiciels standards — pour simplifier vos processus et grandir avec votre activité.",
    "svc.custom.title": "SoftenWise | Développement logiciel sur mesure",
    "svc.mobile.brand": "Développement mobile",
    "svc.mobile.h1": "Développement mobile",
    "svc.mobile.lead": "Applications natives et hybrides orientées produit pour iOS et Android — de la publication store au suivi en production.",
    "svc.mobile.title": "SoftenWise | Développement mobile",
    "svc.integ.brand": "Intégration et automatisation",
    "svc.integ.h1": "Intégration et automatisation",
    "svc.integ.lead": "Nous connectons des systèmes isolés et automatisons les flux de données pour réduire l’erreur manuelle et libérer vos équipes.",
    "svc.integ.title": "SoftenWise | Intégration et automatisation",
    "svc.sec.brand": "Sécurité et audit",
    "svc.sec.h1": "Sécurité et audit",
    "svc.sec.lead": "Nous renforçons vos systèmes face aux cybermenaces tout en accompagnant conformité et audits techniques.",
    "svc.sec.title": "SoftenWise | Sécurité et audit",
    "svc.consult.brand": "Conseil technique",
    "svc.consult.h1": "Conseil technique",
    "svc.consult.lead": "Conseil clair sur l’architecture, le refactoring et l’échelle — pour grandir sans dette technique inutile.",
    "svc.consult.title": "SoftenWise | Conseil technique",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "Renforçons ensemble la discipline d’ingénierie",
    "academy.lead": "SoftenWise Academy place au centre la discipline d’ingénierie et les architectures scalables — pas seulement l’écriture de code.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "Carrières SoftenWise",
    "career.h1": "Vrais produits, fort trafic, croissance mesurable",
    "career.lead": "Chez SoftenWise, vous prenez part aux décisions d’architecture de systèmes à fort trafic et résolvez des problèmes de performance sur des projets réels.",
    "career.title": "SoftenWise | Carrières",
    "partner.brand": "Partenariat venture",
    "partner.h1": "Faisons grandir vos idées avec notre capacité technique",
    "partner.lead": "Nous transformons des visions à fort potentiel en modèles durables via validation technique, MVP et stratégie de croissance.",
    "partner.title": "SoftenWise | Partenariat venture",
    "resources.brand": "Centre de ressources",
    "resources.h1": "Des guides clairs pour les décisions logiciels",
    "resources.lead": "Un ensemble de contenus axés sur les vraies questions des décideurs — sélection, coût et processus.",
    "resources.title": "SoftenWise | Ressources",
    "guide.firm.brand": "Guide",
    "guide.firm.h1": "Comment choisir un partenaire logiciel ?",
    "guide.firm.lead": "Le bon partenaire technologique conditionne la réussite du projet. Nous avons rassemblé les points de contrôle critiques, de l’offre à la qualité technique.",
    "guide.firm.title": "SoftenWise | Choisir un partenaire logiciel",
    "guide.cost.brand": "Guide des coûts",
    "guide.cost.h1": "Comment calcule-t-on le coût d’un logiciel sur mesure ?",
    "guide.cost.lead": "Un cadre pratique pour l’analyse de périmètre, la budgétisation et une livraison transparente.",
    "guide.cost.title": "SoftenWise | Coût du logiciel sur mesure",
    "guide.mobile.brand": "Guide mobile",
    "guide.mobile.h1": "Processus de développement d’application mobile",
    "guide.mobile.lead": "Les produits mobiles réussis naissent de la découverte, des tests et de la discipline de publication — pas seulement du code.",
    "guide.mobile.title": "SoftenWise | Processus d’app mobile",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — Page introuvable",
    "err404.lead": "Cette adresse n’existe peut-être plus ou a été mal saisie. Continuez via l’accueil, les services ou les ressources.",
    "err404.title": "SoftenWise | Page introuvable",
    "err404.home": "Retour à l’accueil",
}

ES = {
    "common.cta.meeting": "Solicitar reunión",
    "common.cta.project": "Agendar discusión de proyecto",
    "common.cta.back_services": "Volver a servicios",
    "common.cta.send": "Enviar solicitud",
    "common.cta.view_guides": "Ver guías",
    "common.contact.h2": "Evaluemos su proyecto juntos",
    "common.contact.p": "Programe una breve reunión técnica para aclarar alcance, calendario y siguientes pasos.",
    "common.contact.name": "Nombre completo",
    "common.contact.email": "Correo electrónico",
    "common.contact.message": "Breve resumen de su proyecto",
    "common.contact.success": "Gracias. Hemos recibido su solicitud y responderemos en breve.",
    "common.proof": "Referencias seleccionadas",
    "common.detail": "En detalle",
    "common.process": "Proceso",
    "common.more": "Continuar",
    "urunler.title": "SoftenWise | Productos",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps y BLOC — el portafolio de productos SoftenWise.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "Productos",
    "urunler.lead": 'De la clínica a los mapas y el móvil: aquí reunimos nuestros productos. Para software a medida o integración, vea nuestros <a href="index.html#solutions">servicios</a>.',
    "urunler.cta1": "Explorar productos",
    "urunler.cta2": "Solicitar reunión",
    "urunler.featured": "Destacados",
    "urunler.jump": "Ir a detalles del producto",
    "urunler.clinic.desc": "Gestione los procesos clínicos desde la cita hasta las finanzas en un solo panel.",
    "urunler.clinic.cta": "Revisar detalles técnicos",
    "urunler.otomini.desc": "Valoración, inspección y escaparate de vehículos de ocasión.",
    "urunler.otomini.cta": "Revisar detalles técnicos",
    "urunler.maps.desc": "SIG empresarial para operaciones de campo: mapas, zonas, rutas y API REST.",
    "urunler.maps.cta": "Resumen y enlaces",
    "urunler.bloc.badge": "App móvil",
    "urunler.bloc.desc": "Aplicación iOS / Android orientada a comunidad y feed social.",
    "urunler.bloc.cta": "Resumen de la app",
    "urunler.kicker.portfolio": "Portafolio",
    "urunler.kicker.eco": "Ecosistema SoftenWise",
    "urunler.visit": "Ir al sitio del producto",
    "urunler.clinic.lead": "Una consola web que centraliza los procesos clínicos, desde citas y seguimiento de pacientes hasta finanzas e informes.",
    "urunler.clinic.b1": "<strong>11 idiomas</strong> e infraestructura multipaís; visibilidad por sucursal",
    "urunler.clinic.b2": "Módulos de paciente y visita, citas, finanzas e informes",
    "urunler.clinic.b3": "Acceso por roles y <strong>registro de auditoría</strong> para trazabilidad",
    "urunler.clinic.b4": "Consola web; opciones SaaS o nube del cliente",
    "urunler.clinic.b5": "<strong>Prueba gratuita de 15 días</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Para policlínicas, centros médicos privados y organizaciones multi-sucursal",
    "urunler.otomini.lead": "Comercio de vehículos de ocasión centrado en la confianza: valoración digital instantánea, inspección transparente y escaparate profesional.",
    "urunler.otomini.b1": "<strong>Valoración inteligente:</strong> valor preliminar en segundos a partir de marca, modelo y equipamiento",
    "urunler.otomini.b2": "<strong>Inspección transparente:</strong> resumen de daños e historial",
    "urunler.otomini.b3": "<strong>Gestión de anuncios:</strong> presentación orientada a galería en el escaparate Otomini",
    "urunler.otomini.b4": "Para concesionarios, redes de dealers y equipos de compraventa",
    "urunler.otomini.b5": "Marca de producto independiente desarrollada por SoftenWise",
    "urunler.maps.lead": "Ecosistema <strong>SIG</strong> empresarial para supervisar operaciones de campo desde un solo panel: mapas, zonas, rutas, informes y API REST.",
    "urunler.maps.b1": "<strong>Panel único:</strong> mapa, árbol de capas, herramientas de dibujo; foco en vivo por dirección / coordenadas",
    "urunler.maps.b2": "Zonas seguras y restringidas (polígonos); historial versionado",
    "urunler.maps.b3": "Geocodificación, rutas, matriz de distancias; GeoJSON / KML e integración <strong>API REST</strong>",
    "urunler.maps.b4": "Teselas XYZ, Nominatim, WMS / WMTS; Google Maps Platform o servicios de mapas internos",
    "urunler.maps.b5": "Arquitectura multi-inquilino, acceso por roles; documentación OpenAPI / Redoc",
    "urunler.maps.b6": "Diseñado para campo, logística y planificación territorial",
    "urunler.bloc.lead": "Aplicación móvil <strong>iOS y Android</strong> orientada a comunidad y feed social — compartir, descubrir e interactuar en un solo producto.",
    "urunler.bloc.b1": "Distribución vía App Store y Google Play",
    "urunler.bloc.b2": "Interfaz adecuada para feed social e interacción comunitaria",
    "urunler.bloc.b3": "Desarrollada con estándares de ingeniería SoftenWise",
    "urunler.bloc.b4": "Ciclo de vida de producto orientado a tiendas",
    "urunler.bloc.b5": "Experiencia nativa para iOS y Android",
    "svc.custom.brand": "Desarrollo de software",
    "svc.custom.h1": "Desarrollo de software a medida",
    "svc.custom.lead": "Construimos plataformas modulares más allá de los paquetes estándar — simplificando procesos y escalando con su negocio.",
    "svc.custom.title": "SoftenWise | Desarrollo de software a medida",
    "svc.mobile.brand": "Desarrollo móvil",
    "svc.mobile.h1": "Desarrollo móvil",
    "svc.mobile.lead": "Apps nativas e híbridas orientadas a producto para iOS y Android — desde la publicación en tiendas hasta el monitoreo en vivo.",
    "svc.mobile.title": "SoftenWise | Desarrollo móvil",
    "svc.integ.brand": "Integración y automatización",
    "svc.integ.h1": "Integración y automatización",
    "svc.integ.lead": "Conectamos sistemas aislados y automatizamos el flujo de datos para reducir errores manuales y liberar a su equipo.",
    "svc.integ.title": "SoftenWise | Integración y automatización",
    "svc.sec.brand": "Seguridad y auditoría",
    "svc.sec.h1": "Seguridad y auditoría",
    "svc.sec.lead": "Reforzamos sus sistemas frente a ciberamenazas y acompañamos cumplimiento y auditorías técnicas.",
    "svc.sec.title": "SoftenWise | Seguridad y auditoría",
    "svc.consult.brand": "Asesoría técnica",
    "svc.consult.h1": "Asesoría técnica",
    "svc.consult.lead": "Asesoría clara sobre arquitectura, refactorización y escala — para crecer sin deuda técnica innecesaria.",
    "svc.consult.title": "SoftenWise | Asesoría técnica",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "Fortalezcamos juntos la disciplina de ingeniería",
    "academy.lead": "SoftenWise Academy centra la disciplina de ingeniería y las arquitecturas escalables — no solo escribir código.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "Carreras SoftenWise",
    "career.h1": "Productos reales, alto tráfico, crecimiento medible",
    "career.lead": "En SoftenWise asume responsabilidad en decisiones de arquitectura de sistemas de alto tráfico y resuelve problemas de rendimiento en proyectos reales.",
    "career.title": "SoftenWise | Carreras",
    "partner.brand": "Alianza venture",
    "partner.h1": "Hagamos crecer sus ideas con nuestra capacidad técnica",
    "partner.lead": "Convertimos visiones de alto potencial en modelos sostenibles mediante validación técnica, MVP y estrategia de crecimiento.",
    "partner.title": "SoftenWise | Alianza venture",
    "resources.brand": "Centro de recursos",
    "resources.h1": "Guías claras para decisiones de software",
    "resources.lead": "Contenidos orientados a preguntas reales de decisores — selección, coste y proceso.",
    "resources.title": "SoftenWise | Recursos",
    "guide.firm.brand": "Guía",
    "guide.firm.h1": "¿Cómo elegir un partner de software?",
    "guide.firm.lead": "El partner tecnológico adecuado condiciona el resultado del proyecto. Reunimos puntos de control críticos desde la oferta hasta la calidad técnica.",
    "guide.firm.title": "SoftenWise | Cómo elegir un partner de software",
    "guide.cost.brand": "Guía de costes",
    "guide.cost.h1": "¿Cómo se calcula el coste del software a medida?",
    "guide.cost.lead": "Un marco práctico para análisis de alcance, planificación de presupuesto y entrega transparente.",
    "guide.cost.title": "SoftenWise | Coste del software a medida",
    "guide.mobile.brand": "Guía móvil",
    "guide.mobile.h1": "Proceso de desarrollo de aplicaciones móviles",
    "guide.mobile.lead": "Los productos móviles exitosos nacen del discovery, las pruebas y la disciplina de publicación — no solo del código.",
    "guide.mobile.title": "SoftenWise | Proceso de app móvil",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — Página no encontrada",
    "err404.lead": "Esta dirección puede no existir o haberse escrito mal. Continúe desde inicio, servicios o recursos.",
    "err404.title": "SoftenWise | Página no encontrada",
    "err404.home": "Volver al inicio",
}

# Continue with IT, NL, PT, RU, AR, AZ in a compact but complete form
IT = {**{k: ES[k] for k in ES}, **{
    "common.cta.meeting": "Richiedi un incontro",
    "common.cta.project": "Prenota una discussione di progetto",
    "common.cta.back_services": "Torna ai servizi",
    "common.cta.send": "Invia richiesta",
    "common.cta.view_guides": "Vedi le guide",
    "common.contact.h2": "Valutiamo insieme il vostro progetto",
    "common.contact.p": "Pianificate un breve confronto tecnico per chiarire perimetro, tempi e passi successivi.",
    "common.contact.name": "Nome e cognome",
    "common.contact.email": "E-mail",
    "common.contact.message": "Breve sintesi del progetto",
    "common.contact.success": "Grazie. Abbiamo ricevuto la richiesta e risponderemo a breve.",
    "common.proof": "Referenze selezionate",
    "common.detail": "Nel dettaglio",
    "common.process": "Processo",
    "common.more": "Continua",
    "urunler.title": "SoftenWise | Prodotti",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps e BLOC — il portafoglio prodotti SoftenWise.",
    "urunler.h1": "Prodotti",
    "urunler.lead": 'Dalla clinica alle mappe e al mobile: qui troviamo i nostri prodotti. Per software su misura o integrazione, vedi i nostri <a href="index.html#solutions">servizi</a>.',
    "urunler.cta1": "Esplora i prodotti",
    "urunler.cta2": "Richiedi un incontro",
    "urunler.featured": "In evidenza",
    "urunler.jump": "Vai ai dettagli prodotto",
    "urunler.clinic.desc": "Gestisci i processi clinici dall’appuntamento alle finanze in un unico pannello.",
    "urunler.clinic.cta": "Esamina i dettagli tecnici",
    "urunler.otomini.desc": "Valutazione, perizia e vetrina per veicoli usati.",
    "urunler.otomini.cta": "Esamina i dettagli tecnici",
    "urunler.maps.desc": "GIS aziendale per operazioni sul campo: mappe, zone, routing e API REST.",
    "urunler.maps.cta": "Sintesi e link",
    "urunler.bloc.badge": "App mobile",
    "urunler.bloc.desc": "Applicazione iOS / Android orientata a community e feed social.",
    "urunler.bloc.cta": "Panoramica dell’app",
    "urunler.kicker.portfolio": "Portafoglio",
    "urunler.kicker.eco": "Ecosistema SoftenWise",
    "urunler.visit": "Vai al sito prodotto",
    "urunler.clinic.lead": "Una console web che centralizza i processi clinici, dagli appuntamenti e dal monitoraggio pazienti a finanze e report.",
    "urunler.clinic.b1": "<strong>11 lingue</strong> e infrastruttura multi-paese; visibilità per filiale",
    "urunler.clinic.b2": "Moduli paziente e visita, appuntamenti, finanze e report",
    "urunler.clinic.b3": "Accesso basato sui ruoli e <strong>audit log</strong> per la tracciabilità",
    "urunler.clinic.b4": "Console web; opzioni SaaS o cloud del cliente",
    "urunler.clinic.b5": "<strong>Prova gratuita di 15 giorni</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Per policlinici, centri medici privati e organizzazioni multi-filiale",
    "urunler.otomini.lead": "Commercio di usati orientato alla fiducia: valutazione digitale istantanea, perizia trasparente e vetrina professionale.",
    "urunler.otomini.b1": "<strong>Valutazione intelligente:</strong> valore preliminare in secondi da marca, modello e allestimento",
    "urunler.otomini.b2": "<strong>Perizia trasparente:</strong> sintesi danni e storico",
    "urunler.otomini.b3": "<strong>Gestione annunci:</strong> presentazione gallery-first sulla vetrina Otomini",
    "urunler.otomini.b4": "Per concessionarie, reti dealer e team di compravendita",
    "urunler.otomini.b5": "Marchio prodotto indipendente sviluppato da SoftenWise",
    "urunler.maps.lead": "Ecosistema <strong>GIS</strong> enterprise per monitorare le operazioni sul campo da un unico pannello: mappe, zone, routing, report e API REST.",
    "urunler.maps.b1": "<strong>Pannello unico:</strong> mappa, albero layer, strumenti di disegno; focus live per indirizzo / coordinate",
    "urunler.maps.b2": "Zone sicure e vietate (poligoni); storico versionato",
    "urunler.maps.b3": "Geocode, routing, matrice distanze; GeoJSON / KML e integrazione <strong>API REST</strong>",
    "urunler.maps.b4": "Tile XYZ, Nominatim, WMS / WMTS; Google Maps Platform o servizi mappe on-prem",
    "urunler.maps.b5": "Architettura multi-tenant, accesso basato sui ruoli; documentazione OpenAPI / Redoc",
    "urunler.maps.b6": "Progettato per campo, logistica e pianificazione territoriale",
    "urunler.bloc.lead": "App mobile <strong>iOS e Android</strong> orientata a community e feed social — condivisione, scoperta e interazione in un solo prodotto.",
    "urunler.bloc.b1": "Distribuzione via App Store e Google Play",
    "urunler.bloc.b2": "Interfaccia adatta a feed social e interazione di community",
    "urunler.bloc.b3": "Sviluppata con standard di engineering SoftenWise",
    "urunler.bloc.b4": "Ciclo di vita prodotto store-first",
    "urunler.bloc.b5": "Esperienza nativa per iOS e Android",
    "svc.custom.brand": "Sviluppo software",
    "svc.custom.h1": "Sviluppo software su misura",
    "svc.custom.lead": "Costruiamo piattaforme modulari oltre i pacchetti standard — semplificando i processi e scalando con il vostro business.",
    "svc.custom.title": "SoftenWise | Sviluppo software su misura",
    "svc.mobile.brand": "Sviluppo mobile",
    "svc.mobile.h1": "Sviluppo mobile",
    "svc.mobile.lead": "App native e ibride product-oriented per iOS e Android — dal rilascio sugli store al monitoraggio live.",
    "svc.mobile.title": "SoftenWise | Sviluppo mobile",
    "svc.integ.brand": "Integrazione e automazione",
    "svc.integ.h1": "Integrazione e automazione",
    "svc.integ.lead": "Collegiamo sistemi isolati e automatizziamo i flussi dati per ridurre errori manuali e liberare il team.",
    "svc.integ.title": "SoftenWise | Integrazione e automazione",
    "svc.sec.brand": "Sicurezza e audit",
    "svc.sec.h1": "Sicurezza e audit",
    "svc.sec.lead": "Rafforziamo i vostri sistemi contro le cyber minacce e supportiamo compliance e audit tecnici.",
    "svc.sec.title": "SoftenWise | Sicurezza e audit",
    "svc.consult.brand": "Consulenza tecnica",
    "svc.consult.h1": "Consulenza tecnica",
    "svc.consult.lead": "Consulenza chiara su architettura, refactoring e scala — per crescere senza debito tecnico inutile.",
    "svc.consult.title": "SoftenWise | Consulenza tecnica",
    "academy.h1": "Rafforziamo insieme la disciplina di engineering",
    "academy.lead": "SoftenWise Academy mette al centro disciplina di engineering e architetture scalabili — non solo scrivere codice.",
    "career.brand": "Carriere SoftenWise",
    "career.h1": "Prodotti reali, alto traffico, crescita misurabile",
    "career.lead": "In SoftenWise assumete responsabilità nelle decisioni architetturali di sistemi ad alto traffico e risolvete problemi di performance su progetti reali.",
    "career.title": "SoftenWise | Carriere",
    "partner.brand": "Partnership venture",
    "partner.h1": "Facciamo crescere le vostre idee con la nostra capacità tecnica",
    "partner.lead": "Trasformiamo visioni ad alto potenziale in modelli sostenibili tramite validazione tecnica, MVP e strategia di crescita.",
    "partner.title": "SoftenWise | Partnership venture",
    "resources.brand": "Centro risorse",
    "resources.h1": "Guide chiare per decisioni sul software",
    "resources.lead": "Contenuti orientati alle domande reali dei decisori — selezione, costo e processo.",
    "resources.title": "SoftenWise | Risorse",
    "guide.firm.brand": "Guida",
    "guide.firm.h1": "Come scegliere un partner software?",
    "guide.firm.lead": "Il partner tecnologico giusto influenza l’esito del progetto. Abbiamo raccolto i checkpoint critici dall’offerta alla qualità tecnica.",
    "guide.firm.title": "SoftenWise | Come scegliere un partner software",
    "guide.cost.brand": "Guida costi",
    "guide.cost.h1": "Come si calcola il costo del software su misura?",
    "guide.cost.lead": "Un quadro pratico per analisi di perimetro, budget e consegna trasparente.",
    "guide.cost.title": "SoftenWise | Costo del software su misura",
    "guide.mobile.brand": "Guida mobile",
    "guide.mobile.h1": "Processo di sviluppo di applicazioni mobili",
    "guide.mobile.lead": "I prodotti mobili di successo nascono da discovery, test e disciplina di rilascio — non solo dal codice.",
    "guide.mobile.title": "SoftenWise | Processo app mobile",
    "err404.h1": "404 — Pagina non trovata",
    "err404.lead": "Questo indirizzo potrebbe non esistere più o essere stato digitato male. Continuate da home, servizi o risorse.",
    "err404.title": "SoftenWise | Pagina non trovata",
    "err404.home": "Torna alla home",
}}

NL = {**{k: DE[k] for k in DE}, **{
    "common.cta.meeting": "Gesprek aanvragen",
    "common.cta.project": "Projectgesprek plannen",
    "common.cta.back_services": "Terug naar diensten",
    "common.cta.send": "Verzoek indienen",
    "common.cta.view_guides": "Gidsen bekijken",
    "common.contact.h2": "Laten we uw project samen beoordelen",
    "common.contact.p": "Plan een kort technisch gesprek om scope, planning en vervolgstappen te verduidelijken.",
    "common.contact.name": "Volledige naam",
    "common.contact.email": "E-mail",
    "common.contact.message": "Korte projectomschrijving",
    "common.contact.success": "Dank u. We hebben uw verzoek ontvangen en reageren spoedig.",
    "common.proof": "Geselecteerde referenties",
    "common.detail": "In detail",
    "common.process": "Proces",
    "common.more": "Vervolg",
    "urunler.title": "SoftenWise | Producten",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps en BLOC — het SoftenWise-productportfolio.",
    "urunler.h1": "Producten",
    "urunler.lead": 'Van kliniek tot kaarten en mobile: hier vindt u onze producten. Voor maatwerksoftware of integratie, zie onze <a href="index.html#solutions">diensten</a>.',
    "urunler.cta1": "Producten bekijken",
    "urunler.cta2": "Gesprek aanvragen",
    "urunler.featured": "Uitgelicht",
    "urunler.jump": "Naar productdetails",
    "urunler.clinic.desc": "Beheer kliniekprocessen van afspraak tot finance in één panel.",
    "urunler.clinic.cta": "Technische details bekijken",
    "urunler.otomini.desc": "Waardebepaling, inspectie en galerij voor occasions.",
    "urunler.otomini.cta": "Technische details bekijken",
    "urunler.maps.desc": "Enterprise-GIS voor veldoperaties: kaarten, zones, routing en REST API.",
    "urunler.maps.cta": "Overzicht en links",
    "urunler.bloc.badge": "Mobiele app",
    "urunler.bloc.desc": "Community- en social-feedgerichte iOS-/Android-app.",
    "urunler.bloc.cta": "App-overzicht",
    "urunler.kicker.portfolio": "Portfolio",
    "urunler.kicker.eco": "SoftenWise-ecosysteem",
    "urunler.visit": "Naar productwebsite",
    "urunler.clinic.lead": "Een webconsole die kliniekprocessen centraliseert — van afspraken en patiëntopvolging tot finance en rapportage.",
    "urunler.clinic.b1": "<strong>11 talen</strong> en multi-country infrastructuur; zichtbaarheid per vestiging",
    "urunler.clinic.b2": "Modules voor patiënt & bezoek, afspraken, finance en rapportage",
    "urunler.clinic.b3": "Rolgebaseerde toegang en <strong>auditlog</strong> voor traceerbaarheid",
    "urunler.clinic.b4": "Webgebaseerd panel; SaaS- of klantcloudopties",
    "urunler.clinic.b5": "<strong>15 dagen gratis proefperiode</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Voor poliklinieken, private medische centra en multi-vestigingsorganisaties",
    "urunler.otomini.lead": "Occasionhandel gericht op vertrouwen: directe digitale waardebepaling, transparante inspectie en professionele galerij.",
    "urunler.otomini.b1": "<strong>Slimme waardebepaling:</strong> voorlopige waarde in seconden op basis van merk, model en uitvoering",
    "urunler.otomini.b2": "<strong>Transparante inspectie:</strong> samenvatting van schade en historie",
    "urunler.otomini.b3": "<strong>Advertentiebeheer:</strong> gallery-first presentatie in de Otomini-vitrine",
    "urunler.otomini.b4": "Voor dealers, dealernetwerken en handels­teams",
    "urunler.otomini.b5": "Onafhankelijk productmerk, ontwikkeld door SoftenWise",
    "urunler.maps.lead": "Enterprise-<strong>GIS</strong>-ecosysteem om veldoperaties vanuit één panel te volgen: kaarten, zones, routing, rapportage en REST API.",
    "urunler.maps.b1": "<strong>Eén panel:</strong> kaart, laagboom, tekentools; live focus via adres / coördinaten",
    "urunler.maps.b2": "Veilige en verboden zones (polygonen); geversioneerde wijzigingsgeschiedenis",
    "urunler.maps.b3": "Geocode, routing, afstandsmatrix; GeoJSON / KML en <strong>REST API</strong>-integratie",
    "urunler.maps.b4": "XYZ-tiles, Nominatim, WMS / WMTS; Google Maps Platform of interne kartdiensten",
    "urunler.maps.b5": "Multi-tenant architectuur, rolgebaseerde toegang; OpenAPI / Redoc-documentatie",
    "urunler.maps.b6": "Ontworpen voor veld, logistiek en gebiedsplanning",
    "urunler.bloc.lead": "Community- en social-feedgerichte <strong>iOS- en Android</strong>-app — delen, ontdekken en interactie in één product.",
    "urunler.bloc.b1": "Distributie via App Store en Google Play",
    "urunler.bloc.b2": "Interface geschikt voor social feed en community-interactie",
    "urunler.bloc.b3": "Gebouwd volgens SoftenWise-engineeringstandaarden",
    "urunler.bloc.b4": "Store-first productlevenscyclus",
    "urunler.bloc.b5": "Native ervaring voor iOS en Android",
    "svc.custom.brand": "Softwareontwikkeling",
    "svc.custom.h1": "Maatwerksoftware",
    "svc.custom.lead": "We bouwen modulaire platforms voorbij standaardpakketten — processen vereenvoudigen en meegroeien met uw business.",
    "svc.custom.title": "SoftenWise | Maatwerksoftware",
    "svc.mobile.brand": "Mobiele ontwikkeling",
    "svc.mobile.h1": "Mobiele ontwikkeling",
    "svc.mobile.lead": "Productgerichte native en hybride apps voor iOS en Android — van store-release tot live monitoring.",
    "svc.mobile.title": "SoftenWise | Mobiele ontwikkeling",
    "svc.integ.brand": "Integratie & automatisering",
    "svc.integ.h1": "Integratie & automatisering",
    "svc.integ.lead": "We verbinden losse systemen en automatiseren datastromen om handmatige fouten te verminderen en teams vrij te maken.",
    "svc.integ.title": "SoftenWise | Integratie & automatisering",
    "svc.sec.brand": "Security & audit",
    "svc.sec.h1": "Security & audit",
    "svc.sec.lead": "We versterken uw systemen tegen cyberdreigingen en ondersteunen compliance en technische audits.",
    "svc.sec.title": "SoftenWise | Security & audit",
    "svc.consult.brand": "Technisch advies",
    "svc.consult.h1": "Technisch advies",
    "svc.consult.lead": "Helder advies over architectuur, refactoring en schaal — groeien zonder onnodige technische schuld.",
    "svc.consult.title": "SoftenWise | Technisch advies",
    "academy.h1": "Versterk samen engineeringdiscipline",
    "academy.lead": "SoftenWise Academy stelt engineeringdiscipline en schaalbare systeemarchitectuur centraal — niet alleen code schrijven.",
    "career.brand": "Carrière SoftenWise",
    "career.h1": "Echte producten, hoog verkeer, meetbare groei",
    "career.lead": "Bij SoftenWise neemt u verantwoordelijkheid in architectuurbeslissingen voor hoog-verkeer systemen en lost u performance- en schaalproblemen op in echte projecten.",
    "career.title": "SoftenWise | Carrière",
    "partner.brand": "Venture partnership",
    "partner.h1": "Laat uw ideeën groeien met onze technische capaciteit",
    "partner.lead": "We zetten kansrijke visies om in duurzame modellen via technische validatie, MVP en groeistrategie.",
    "partner.title": "SoftenWise | Venture partnership",
    "resources.brand": "Resourcecentrum",
    "resources.h1": "Duidelijke gidsen voor softwarebeslissingen",
    "resources.lead": "Content gericht op echte vragen van beslissers — selectie, kosten en proces.",
    "resources.title": "SoftenWise | Bronnen",
    "guide.firm.brand": "Gids",
    "guide.firm.h1": "Hoe kiest u een softwarepartner?",
    "guide.firm.lead": "De juiste technologiepartner bepaalt het projectsucces. We bundelden kritieke checkpoints van offerte tot technische kwaliteit.",
    "guide.firm.title": "SoftenWise | Softwarepartner kiezen",
    "guide.cost.brand": "Kostengids",
    "guide.cost.h1": "Hoe wordt de kostprijs van maatwerksoftware berekend?",
    "guide.cost.lead": "Een praktisch kader voor scope-analyse, budgetplanning en transparante oplevering.",
    "guide.cost.title": "SoftenWise | Kosten maatwerksoftware",
    "guide.mobile.brand": "Mobiele gids",
    "guide.mobile.h1": "Proces voor ontwikkeling van mobiele apps",
    "guide.mobile.lead": "Succesvolle mobiele producten ontstaan uit discovery, testen en release-discipline — niet alleen uit code.",
    "guide.mobile.title": "SoftenWise | Mobiele app-proces",
    "err404.h1": "404 — Pagina niet gevonden",
    "err404.lead": "Dit adres bestaat mogelijk niet meer of is verkeerd ingevoerd. Ga verder via home, diensten of bronnen.",
    "err404.title": "SoftenWise | Pagina niet gevonden",
    "err404.home": "Terug naar home",
}}

PT = {**{k: ES[k] for k in ES}, **{
    "common.cta.meeting": "Pedir reunião",
    "common.cta.project": "Agendar discussão de projeto",
    "common.cta.back_services": "Voltar aos serviços",
    "common.cta.send": "Enviar pedido",
    "common.cta.view_guides": "Ver guias",
    "common.contact.h2": "Vamos avaliar o seu projeto em conjunto",
    "common.contact.p": "Agende uma breve conversa técnica para clarificar âmbito, calendário e próximos passos.",
    "common.contact.name": "Nome completo",
    "common.contact.email": "E-mail",
    "common.contact.message": "Breve resumo do projeto",
    "common.contact.success": "Obrigado. Recebemos o seu pedido e responderemos em breve.",
    "common.proof": "Referências selecionadas",
    "common.detail": "Em detalhe",
    "common.process": "Processo",
    "common.more": "Continuar",
    "urunler.title": "SoftenWise | Produtos",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps e BLOC — o portefólio de produtos SoftenWise.",
    "urunler.h1": "Produtos",
    "urunler.lead": 'Da clínica aos mapas e ao mobile: reunimos aqui os nossos produtos. Para software sob medida ou integração, veja os nossos <a href="index.html#solutions">serviços</a>.',
    "urunler.cta1": "Explorar produtos",
    "urunler.cta2": "Pedir reunião",
    "urunler.featured": "Destaques",
    "urunler.jump": "Ir para detalhes do produto",
    "urunler.clinic.desc": "Faça a gestão dos processos clínicos da marcação às finanças num único painel.",
    "urunler.clinic.cta": "Ver detalhes técnicos",
    "urunler.otomini.desc": "Avaliação, inspeção e vitrine de veículos usados.",
    "urunler.otomini.cta": "Ver detalhes técnicos",
    "urunler.maps.desc": "SIG empresarial para operações de campo: mapas, zonas, rotas e API REST.",
    "urunler.maps.cta": "Resumo e ligações",
    "urunler.bloc.badge": "App móvel",
    "urunler.bloc.desc": "Aplicação iOS / Android orientada a comunidade e feed social.",
    "urunler.bloc.cta": "Resumo da app",
    "urunler.kicker.portfolio": "Portefólio",
    "urunler.kicker.eco": "Ecossistema SoftenWise",
    "urunler.visit": "Ir ao site do produto",
    "urunler.clinic.lead": "Uma consola web que centraliza os processos clínicos, desde marcações e acompanhamento de pacientes até finanças e relatórios.",
    "urunler.clinic.b1": "<strong>11 idiomas</strong> e infraestrutura multi-país; visibilidade por filial",
    "urunler.clinic.b2": "Módulos de paciente e visita, marcações, finanças e relatórios",
    "urunler.clinic.b3": "Acesso baseado em funções e <strong>registo de auditoria</strong> para rastreabilidade",
    "urunler.clinic.b4": "Consola web; opções SaaS ou cloud do cliente",
    "urunler.clinic.b5": "<strong>Teste gratuito de 15 dias</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Para policlínicas, centros médicos privados e organizações multi-filial",
    "urunler.otomini.lead": "Comércio de usados centrado na confiança: avaliação digital instantânea, inspeção transparente e vitrine profissional.",
    "urunler.otomini.b1": "<strong>Avaliação inteligente:</strong> valor preliminar em segundos a partir de marca, modelo e equipamento",
    "urunler.otomini.b2": "<strong>Inspeção transparente:</strong> resumo de danos e histórico",
    "urunler.otomini.b3": "<strong>Gestão de anúncios:</strong> apresentação gallery-first na vitrine Otomini",
    "urunler.otomini.b4": "Para concessionários, redes de dealers e equipas de compra e venda",
    "urunler.otomini.b5": "Marca de produto independente desenvolvida pela SoftenWise",
    "urunler.maps.lead": "Ecossistema <strong>SIG</strong> empresarial para monitorizar operações de campo a partir de um único painel: mapas, zonas, rotas, relatórios e API REST.",
    "urunler.maps.b1": "<strong>Painel único:</strong> mapa, árvore de camadas, ferramentas de desenho; foco em direto por morada / coordenadas",
    "urunler.maps.b2": "Zonas seguras e restritas (polígonos); histórico versionado",
    "urunler.maps.b3": "Geocode, rotas, matriz de distâncias; GeoJSON / KML e integração <strong>API REST</strong>",
    "urunler.maps.b4": "Tiles XYZ, Nominatim, WMS / WMTS; Google Maps Platform ou serviços de mapas internos",
    "urunler.maps.b5": "Arquitetura multi-inquilino, acesso baseado em funções; documentação OpenAPI / Redoc",
    "urunler.maps.b6": "Concebido para campo, logística e planeamento territorial",
    "urunler.bloc.lead": "Aplicação móvel <strong>iOS e Android</strong> orientada a comunidade e feed social — partilha, descoberta e interação num só produto.",
    "urunler.bloc.b1": "Distribuição via App Store e Google Play",
    "urunler.bloc.b2": "Interface adequada a feed social e interação de comunidade",
    "urunler.bloc.b3": "Desenvolvida com padrões de engenharia SoftenWise",
    "urunler.bloc.b4": "Ciclo de vida de produto orientado a lojas",
    "urunler.bloc.b5": "Experiência nativa para iOS e Android",
    "svc.custom.brand": "Desenvolvimento de software",
    "svc.custom.h1": "Desenvolvimento de software sob medida",
    "svc.custom.lead": "Construímos plataformas modulares além dos pacotes padrão — simplificando processos e escalando com o seu negócio.",
    "svc.custom.title": "SoftenWise | Software sob medida",
    "svc.mobile.brand": "Desenvolvimento mobile",
    "svc.mobile.h1": "Desenvolvimento mobile",
    "svc.mobile.lead": "Apps nativas e híbridas orientadas a produto para iOS e Android — da publicação nas lojas ao monitoramento em produção.",
    "svc.mobile.title": "SoftenWise | Desenvolvimento mobile",
    "svc.integ.brand": "Integração e automatização",
    "svc.integ.h1": "Integração e automatização",
    "svc.integ.lead": "Ligamos sistemas isolados e automatizamos fluxos de dados para reduzir erro manual e libertar a equipa.",
    "svc.integ.title": "SoftenWise | Integração e automatização",
    "svc.sec.brand": "Segurança e auditoria",
    "svc.sec.h1": "Segurança e auditoria",
    "svc.sec.lead": "Reforçamos os seus sistemas contra ciberameaças e acompanhamos conformidade e auditorias técnicas.",
    "svc.sec.title": "SoftenWise | Segurança e auditoria",
    "svc.consult.brand": "Consultoria técnica",
    "svc.consult.h1": "Consultoria técnica",
    "svc.consult.lead": "Consultoria clara sobre arquitetura, refactoring e escala — para crescer sem dívida técnica desnecessária.",
    "svc.consult.title": "SoftenWise | Consultoria técnica",
    "academy.h1": "Vamos reforçar juntos a disciplina de engenharia",
    "academy.lead": "A SoftenWise Academy centra a disciplina de engenharia e arquiteturas escaláveis — não apenas escrever código.",
    "career.brand": "Carreiras SoftenWise",
    "career.h1": "Produtos reais, alto tráfego, crescimento mensurável",
    "career.lead": "Na SoftenWise assume responsabilidade em decisões de arquitetura de sistemas de alto tráfego e resolve problemas de desempenho em projetos reais.",
    "career.title": "SoftenWise | Carreiras",
    "partner.brand": "Parceria venture",
    "partner.h1": "Façamos crescer as suas ideias com a nossa capacidade técnica",
    "partner.lead": "Transformamos visões de elevado potencial em modelos sustentáveis através de validação técnica, MVP e estratégia de crescimento.",
    "partner.title": "SoftenWise | Parceria venture",
    "resources.brand": "Centro de recursos",
    "resources.h1": "Guias claros para decisões de software",
    "resources.lead": "Conteúdos focados em perguntas reais de decisores — seleção, custo e processo.",
    "resources.title": "SoftenWise | Recursos",
    "guide.firm.brand": "Guia",
    "guide.firm.h1": "Como escolher um parceiro de software?",
    "guide.firm.lead": "O parceiro tecnológico certo condiciona o sucesso do projeto. Compilámos pontos de controlo críticos da proposta à qualidade técnica.",
    "guide.firm.title": "SoftenWise | Como escolher um parceiro de software",
    "guide.cost.brand": "Guia de custos",
    "guide.cost.h1": "Como se calcula o custo do software sob medida?",
    "guide.cost.lead": "Um quadro prático para análise de âmbito, planeamento orçamental e entrega transparente.",
    "guide.cost.title": "SoftenWise | Custo do software sob medida",
    "guide.mobile.brand": "Guia mobile",
    "guide.mobile.h1": "Processo de desenvolvimento de aplicações móveis",
    "guide.mobile.lead": "Produtos móveis de sucesso nascem de discovery, testes e disciplina de publicação — não apenas de código.",
    "guide.mobile.title": "SoftenWise | Processo de app móvel",
    "err404.h1": "404 — Página não encontrada",
    "err404.lead": "Este endereço pode já não existir ou ter sido escrito incorretamente. Continue a partir do início, serviços ou recursos.",
    "err404.title": "SoftenWise | Página não encontrada",
    "err404.home": "Voltar ao início",
}}

# RU, AR, AZ - write complete from EN structure via dedicated dicts (file already long - use Task? No, finish here)
# I'll load EN keys from locales and apply translations in a second file part via exec

print("packs defined", len(DE), len(FR), len(ES), len(IT), len(NL), len(PT))
