# -*- coding: utf-8 -*-
"""Apply full 11-language page packs into js/locales.js."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALES = ROOT / "js" / "locales.js"

# Load DE/FR/ES/IT/NL/PT from partial module
ns: dict = {"__file__": str(ROOT / "scripts" / "_packs_partial.py"), "__name__": "_packs_partial"}
exec((ROOT / "scripts" / "_packs_partial.py").read_text(encoding="utf-8"), ns)
DE, FR, ES, IT, NL, PT = ns["DE"], ns["FR"], ns["ES"], ns["IT"], ns["NL"], ns["PT"]

RU = {
    "common.cta.meeting": "Запросить встречу",
    "common.cta.project": "Запланировать обсуждение проекта",
    "common.cta.back_services": "К услугам",
    "common.cta.send": "Отправить запрос",
    "common.cta.view_guides": "Смотреть материалы",
    "common.contact.h2": "Давайте вместе оценим ваш проект",
    "common.contact.p": "Запланируйте короткую техническую встречу, чтобы уточнить объём, сроки и следующие шаги.",
    "common.contact.name": "ФИО",
    "common.contact.email": "Эл. почта",
    "common.contact.message": "Краткое описание проекта",
    "common.contact.success": "Спасибо. Мы получили запрос и ответим в ближайшее время.",
    "common.proof": "Избранные клиенты",
    "common.detail": "Подробнее",
    "common.process": "Процесс",
    "common.more": "Далее",
    "urunler.title": "SoftenWise | Продукты",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps и BLOC — продуктовый портфель SoftenWise.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "Продукты",
    "urunler.lead": 'От клиники до карт и мобильных приложений: наши продукты собраны здесь. Для заказного ПО или интеграции см. наши <a href="index.html#solutions">услуги</a>.',
    "urunler.cta1": "Смотреть продукты",
    "urunler.cta2": "Запросить встречу",
    "urunler.featured": "Избранное",
    "urunler.jump": "К деталям продукта",
    "urunler.clinic.desc": "Управляйте клиническими процессами от записи до финансов в одной панели.",
    "urunler.clinic.cta": "Изучить технические детали",
    "urunler.otomini.desc": "Оценка, экспертиза и витрина автомобилей с пробегом.",
    "urunler.otomini.cta": "Изучить технические детали",
    "urunler.maps.desc": "Корпоративная ГИС для полевых операций: карты, зоны, маршруты и REST API.",
    "urunler.maps.cta": "Обзор и ссылки",
    "urunler.bloc.badge": "Мобильное приложение",
    "urunler.bloc.desc": "iOS / Android приложение для сообщества и социальной ленты.",
    "urunler.bloc.cta": "Обзор приложения",
    "urunler.kicker.portfolio": "Портфель",
    "urunler.kicker.eco": "Экосистема SoftenWise",
    "urunler.visit": "Перейти на сайт продукта",
    "urunler.clinic.lead": "Веб-консоль, которая централизует клинические процессы — от записи и ведения пациентов до финансов и отчётности.",
    "urunler.clinic.b1": "<strong>11 языков</strong> и мультинациональная инфраструктура; видимость по филиалам",
    "urunler.clinic.b2": "Модули пациентов и визитов, записи, финансов и отчётности",
    "urunler.clinic.b3": "Ролевой доступ и <strong>журнал аудита</strong> для прослеживаемости",
    "urunler.clinic.b4": "Веб-панель; варианты SaaS или облако заказчика",
    "urunler.clinic.b5": "<strong>15 дней бесплатного пробного периода</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Для поликлиник, частных медцентров и мультифилиальных организаций",
    "urunler.otomini.lead": "Торговля автомобилями с пробегом на основе доверия: мгновенная цифровая оценка, прозрачная экспертиза и профессиональная витрина.",
    "urunler.otomini.b1": "<strong>Умная оценка:</strong> предварительная стоимость за секунды по марке, модели и комплектации",
    "urunler.otomini.b2": "<strong>Прозрачная экспертиза:</strong> сводка повреждений и истории",
    "urunler.otomini.b3": "<strong>Управление объявлениями:</strong> gallery-first презентация на витрине Otomini",
    "urunler.otomini.b4": "Для автосалонов, дилерских сетей и команд купли-продажи",
    "urunler.otomini.b5": "Независимый продуктовый бренд, разработанный SoftenWise",
    "urunler.maps.lead": "Корпоративная экосистема <strong>ГИС</strong> для мониторинга полевых операций с одной панели: карты, зоны, маршруты, отчётность и REST API.",
    "urunler.maps.b1": "<strong>Единая панель:</strong> карта, дерево слоёв, инструменты рисования; живой фокус по адресу / координатам",
    "urunler.maps.b2": "Безопасные и запретные зоны (полигоны); версионированная история изменений",
    "urunler.maps.b3": "Геокод, маршруты, матрица расстояний; GeoJSON / KML и интеграция <strong>REST API</strong>",
    "urunler.maps.b4": "XYZ-тайлы, Nominatim, WMS / WMTS; Google Maps Platform или внутренние картографические сервисы",
    "urunler.maps.b5": "Мультитенантная архитектура, ролевой доступ; документация OpenAPI / Redoc",
    "urunler.maps.b6": "Для поля, логистики и территориального планирования",
    "urunler.bloc.lead": "Мобильное приложение <strong>iOS и Android</strong> для сообщества и социальной ленты — обмен, открытие и взаимодействие в одном продукте.",
    "urunler.bloc.b1": "Дистрибуция через App Store и Google Play",
    "urunler.bloc.b2": "Интерфейс для социальной ленты и взаимодействия сообщества",
    "urunler.bloc.b3": "Разработано по инженерным стандартам SoftenWise",
    "urunler.bloc.b4": "Жизненный цикл продукта с приоритетом магазинов",
    "urunler.bloc.b5": "Нативный опыт для iOS и Android",
    "svc.custom.brand": "Разработка ПО",
    "svc.custom.h1": "Заказная разработка ПО",
    "svc.custom.lead": "Мы создаём модульные платформы за пределами коробочных решений — упрощая процессы и масштабируясь вместе с бизнесом.",
    "svc.custom.title": "SoftenWise | Заказная разработка ПО",
    "svc.mobile.brand": "Мобильная разработка",
    "svc.mobile.h1": "Мобильная разработка",
    "svc.mobile.lead": "Продуктово-ориентированные native и hybrid приложения для iOS и Android — от публикации в магазинах до мониторинга в проде.",
    "svc.mobile.title": "SoftenWise | Мобильная разработка",
    "svc.integ.brand": "Интеграция и автоматизация",
    "svc.integ.h1": "Интеграция и автоматизация",
    "svc.integ.lead": "Мы связываем разрозненные системы и автоматизируем потоки данных, снижая ручные ошибки и освобождая команду.",
    "svc.integ.title": "SoftenWise | Интеграция и автоматизация",
    "svc.sec.brand": "Безопасность и аудит",
    "svc.sec.h1": "Безопасность и аудит",
    "svc.sec.lead": "Мы усиливаем системы против киберугроз и сопровождаем соответствие требованиям и технические аудиты.",
    "svc.sec.title": "SoftenWise | Безопасность и аудит",
    "svc.consult.brand": "Технический консалтинг",
    "svc.consult.h1": "Технический консалтинг",
    "svc.consult.lead": "Чёткие рекомендации по архитектуре, рефакторингу и масштабированию — рост без лишнего техдолга.",
    "svc.consult.title": "SoftenWise | Технический консалтинг",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "Укрепим вместе инженерную дисциплину",
    "academy.lead": "SoftenWise Academy ставит в центр инженерную дисциплину и масштабируемые архитектуры — не только написание кода.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "Карьера SoftenWise",
    "career.h1": "Реальные продукты, высокий трафик, измеримый рост",
    "career.lead": "В SoftenWise вы участвуете в архитектурных решениях высоконагруженных систем и решаете задачи производительности на реальных проектах.",
    "career.title": "SoftenWise | Карьера",
    "partner.brand": "Венчурное партнёрство",
    "partner.h1": "Вырастим ваши идеи нашей технической мощностью",
    "partner.lead": "Мы превращаем перспективные идеи в устойчивые модели через техническую валидацию, MVP и стратегию роста.",
    "partner.title": "SoftenWise | Венчурное партнёрство",
    "resources.brand": "Центр ресурсов",
    "resources.h1": "Понятные гайды для решений по ПО",
    "resources.lead": "Контент по реальным вопросам заказчиков — выбор, стоимость и процесс.",
    "resources.title": "SoftenWise | Ресурсы",
    "guide.firm.brand": "Гайд",
    "guide.firm.h1": "Как выбрать подрядчика по ПО?",
    "guide.firm.lead": "Правильный технологический партнёр определяет исход проекта. Мы собрали критические контрольные точки — от предложения до технического качества.",
    "guide.firm.title": "SoftenWise | Как выбрать подрядчика по ПО",
    "guide.cost.brand": "Гайд по стоимости",
    "guide.cost.h1": "Как рассчитывается стоимость заказного ПО?",
    "guide.cost.lead": "Практическая рамка для анализа объёма, бюджета и прозрачной поставки.",
    "guide.cost.title": "SoftenWise | Стоимость заказного ПО",
    "guide.mobile.brand": "Мобильный гайд",
    "guide.mobile.h1": "Процесс разработки мобильных приложений",
    "guide.mobile.lead": "Успешные мобильные продукты рождаются из discovery, тестов и дисциплины релиза — не только из кода.",
    "guide.mobile.title": "SoftenWise | Процесс мобильной разработки",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — Страница не найдена",
    "err404.lead": "Адрес мог устареть или быть введён с ошибкой. Продолжите с главной, услуг или ресурсов.",
    "err404.title": "SoftenWise | Страница не найдена",
    "err404.home": "На главную",
}

AR = {
    "common.cta.meeting": "اطلب اجتماعًا",
    "common.cta.project": "حدد موعد مناقشة المشروع",
    "common.cta.back_services": "العودة إلى الخدمات",
    "common.cta.send": "إرسال الطلب",
    "common.cta.view_guides": "عرض الأدلة",
    "common.contact.h2": "لنقيّم مشروعك معًا",
    "common.contact.p": "حدد اجتماعًا تقنيًا قصيرًا لتوضيح النطاق والجدول والخطوات التالية.",
    "common.contact.name": "الاسم الكامل",
    "common.contact.email": "البريد الإلكتروني",
    "common.contact.message": "ملخص موجز عن مشروعك",
    "common.contact.success": "شكرًا لك. استلمنا طلبك وسنرد قريبًا.",
    "common.proof": "مراجع مختارة",
    "common.detail": "بالتفصيل",
    "common.process": "العملية",
    "common.more": "المزيد",
    "urunler.title": "SoftenWise | المنتجات",
    "urunler.desc": "SoftenWise Clinic وOtomini وSoftenWise Maps وBLOC — محفظة منتجات SoftenWise.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "المنتجات",
    "urunler.lead": 'من العيادة إلى الخرائط والجوال: جمعنا منتجاتنا هنا. للبرمجيات المخصصة أو التكامل، اطّلع على <a href="index.html#solutions">خدماتنا</a>.',
    "urunler.cta1": "استكشف المنتجات",
    "urunler.cta2": "اطلب اجتماعًا",
    "urunler.featured": "مميز",
    "urunler.jump": "الانتقال إلى تفاصيل المنتج",
    "urunler.clinic.desc": "أدِر عمليات العيادة من الموعد إلى المالية في لوحة واحدة.",
    "urunler.clinic.cta": "راجع التفاصيل التقنية",
    "urunler.otomini.desc": "تقييم وفحص ومعرض للسيارات المستعملة.",
    "urunler.otomini.cta": "راجع التفاصيل التقنية",
    "urunler.maps.desc": "نظم معلومات جغرافية مؤسسية للعمليات الميدانية: خرائط ومناطق ومسارات وواجهة REST.",
    "urunler.maps.cta": "ملخص وروابط",
    "urunler.bloc.badge": "تطبيق جوال",
    "urunler.bloc.desc": "تطبيق iOS / Android موجّه للمجتمع والتدفق الاجتماعي.",
    "urunler.bloc.cta": "نظرة عامة على التطبيق",
    "urunler.kicker.portfolio": "المحفظة",
    "urunler.kicker.eco": "منظومة SoftenWise",
    "urunler.visit": "انتقل إلى موقع المنتج",
    "urunler.clinic.lead": "لوحة ويب تُمركز عمليات العيادة من المواعيد ومتابعة المرضى إلى المالية والتقارير.",
    "urunler.clinic.b1": "<strong>11 لغة</strong> وبنية متعددة الدول؛ رؤية على مستوى الفرع",
    "urunler.clinic.b2": "وحدات المريض والزيارة والمواعيد والمالية والتقارير",
    "urunler.clinic.b3": "وصول حسب الأدوار و<strong>سجل تدقيق</strong> للتتبّع",
    "urunler.clinic.b4": "لوحة ويب؛ خيارات SaaS أو سحابة العميل",
    "urunler.clinic.b5": "<strong>تجربة مجانية 15 يومًا</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "للعيادات والمراكز الطبية الخاصة والمنظمات متعددة الفروع",
    "urunler.otomini.lead": "تجارة سيارات مستعملة قائمة على الثقة: تقييم رقمي فوري وفحص شفاف ومعرض احترافي.",
    "urunler.otomini.b1": "<strong>تقييم ذكي:</strong> قيمة أولية خلال ثوانٍ من العلامة والطراز والتجهيز",
    "urunler.otomini.b2": "<strong>فحص شفاف:</strong> ملخص الأضرار والسجل",
    "urunler.otomini.b3": "<strong>إدارة الإعلانات:</strong> عرض بمعيار المعرض في واجهة Otomini",
    "urunler.otomini.b4": "للمعارض وشبكات الوكلاء وفرق البيع والشراء",
    "urunler.otomini.b5": "علامة منتج مستقلة طورتها SoftenWise",
    "urunler.maps.lead": "منظومة <strong>GIS</strong> مؤسسية لمتابعة العمليات الميدانية من لوحة واحدة: خرائط ومناطق ومسارات وتقارير وواجهة REST.",
    "urunler.maps.b1": "<strong>لوحة واحدة:</strong> خريطة وشجرة طبقات وأدوات رسم؛ تركيز مباشر بالعنوان / الإحداثيات",
    "urunler.maps.b2": "مناطق آمنة ومحظورة (مضلعات)؛ سجل تغييرات بإصدارات",
    "urunler.maps.b3": "ترميز جغرافي ومسارات ومصفوفة مسافات؛ GeoJSON / KML وتكامل <strong>REST API</strong>",
    "urunler.maps.b4": "بلاطات XYZ وNominatim وWMS / WMTS؛ Google Maps Platform أو خدمات خرائط داخلية",
    "urunler.maps.b5": "هندسة متعددة المستأجرين ووصول حسب الأدوار؛ توثيق OpenAPI / Redoc",
    "urunler.maps.b6": "مصمم للميدان واللوجستيات وتخطيط المناطق",
    "urunler.bloc.lead": "تطبيق جوال لـ <strong>iOS وAndroid</strong> موجّه للمجتمع والتدفق الاجتماعي — مشاركة واكتشاف وتفاعل في منتج واحد.",
    "urunler.bloc.b1": "التوزيع عبر App Store وGoogle Play",
    "urunler.bloc.b2": "واجهة مناسبة للتدفق الاجتماعي وتفاعل المجتمع",
    "urunler.bloc.b3": "طُوّر وفق معايير هندسة SoftenWise",
    "urunler.bloc.b4": "دورة حياة منتج تعتمد المتاجر أولاً",
    "urunler.bloc.b5": "تجربة أصلية لـ iOS وAndroid",
    "svc.custom.brand": "تطوير البرمجيات",
    "svc.custom.h1": "تطوير برمجيات مخصصة",
    "svc.custom.lead": "نبني منصات معيارية تتجاوز الحزم الجاهزة — لتبسيط عملياتك والنمو مع عملك.",
    "svc.custom.title": "SoftenWise | تطوير برمجيات مخصصة",
    "svc.mobile.brand": "تطوير الجوال",
    "svc.mobile.h1": "تطوير الجوال",
    "svc.mobile.lead": "تطبيقات أصلية وهجينة موجّهة للمنتج لـ iOS وAndroid — من النشر في المتاجر إلى المراقبة الحية.",
    "svc.mobile.title": "SoftenWise | تطوير الجوال",
    "svc.integ.brand": "التكامل والأتمتة",
    "svc.integ.h1": "التكامل والأتمتة",
    "svc.integ.lead": "نربط الأنظمة المنفصلة ونؤتمت تدفق البيانات لتقليل الخطأ اليدوي وتحرير فريقك.",
    "svc.integ.title": "SoftenWise | التكامل والأتمتة",
    "svc.sec.brand": "الأمن والتدقيق",
    "svc.sec.h1": "الأمن والتدقيق",
    "svc.sec.lead": "نعزّز أنظمتك أمام التهديدات السيبرانية ونرافق الامتثال والتدقيق التقني.",
    "svc.sec.title": "SoftenWise | الأمن والتدقيق",
    "svc.consult.brand": "استشارات تقنية",
    "svc.consult.h1": "استشارات تقنية",
    "svc.consult.lead": "استشارة واضحة حول المعمارية وإعادة الهيكلة والتوسع — للنمو دون دين تقني غير ضروري.",
    "svc.consult.title": "SoftenWise | استشارات تقنية",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "لنعزّز معًا انضباط الهندسة",
    "academy.lead": "SoftenWise Academy تضع انضباط الهندسة والبنى القابلة للتوسع في المركز — وليس مجرد كتابة الشيفرة.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "وظائف SoftenWise",
    "career.h1": "منتجات حقيقية، حركة مرور عالية، نمو قابل للقياس",
    "career.lead": "في SoftenWise تتحمل مسؤولية قرارات المعمارية لأنظمة عالية الحركة وتحل مشكلات الأداء في مشاريع حقيقية.",
    "career.title": "SoftenWise | الوظائف",
    "partner.brand": "شراكة استثمارية",
    "partner.h1": "لننمِّ أفكارك بقدرتنا التقنية",
    "partner.lead": "نحوّل الرؤى ذات الإمكانات العالية إلى نماذج مستدامة عبر التحقق التقني وMVP واستراتيجية النمو.",
    "partner.title": "SoftenWise | شراكة استثمارية",
    "resources.brand": "مركز الموارد",
    "resources.h1": "أدلة واضحة لقرارات البرمجيات",
    "resources.lead": "محتوى موجّه لأسئلة صناع القرار الحقيقية — الاختيار والتكلفة والعملية.",
    "resources.title": "SoftenWise | الموارد",
    "guide.firm.brand": "دليل",
    "guide.firm.h1": "كيف تختار شريك برمجيات؟",
    "guide.firm.lead": "الشريك التقني الصحيح يحدد نتيجة المشروع. جمعنا نقاط تحقق حرجة من العرض إلى الجودة التقنية.",
    "guide.firm.title": "SoftenWise | كيف تختار شريك برمجيات",
    "guide.cost.brand": "دليل التكلفة",
    "guide.cost.h1": "كيف تُحسب تكلفة البرمجيات المخصصة؟",
    "guide.cost.lead": "إطار عملي لتحليل النطاق وتخطيط الميزانية والتسليم الشفاف.",
    "guide.cost.title": "SoftenWise | تكلفة البرمجيات المخصصة",
    "guide.mobile.brand": "دليل الجوال",
    "guide.mobile.h1": "عملية تطوير تطبيقات الجوال",
    "guide.mobile.lead": "منتجات الجوال الناجحة تنشأ من الاستكشاف والاختبار وانضباط النشر — وليس من الشيفرة وحدها.",
    "guide.mobile.title": "SoftenWise | عملية تطبيق الجوال",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — الصفحة غير موجودة",
    "err404.lead": "قد لا يعود هذا العنوان موجودًا أو كُتب بشكل خاطئ. تابع من الصفحة الرئيسية أو الخدمات أو الموارد.",
    "err404.title": "SoftenWise | الصفحة غير موجودة",
    "err404.home": "العودة للرئيسية",
}

AZ = {
    "common.cta.meeting": "Görüş sorğusu",
    "common.cta.project": "Layihə görüşü planlaşdırın",
    "common.cta.back_services": "Xidmətlərə qayıt",
    "common.cta.send": "Sorğunu göndərin",
    "common.cta.view_guides": "Bələdçilərə baxın",
    "common.contact.h2": "Layihənizi birlikdə qiymətləndirək",
    "common.contact.p": "Əhatəni, vaxt planını və növbəti addımı netləşdirmək üçün qısa texniki görüş planlaşdıra bilərsiniz.",
    "common.contact.name": "Ad Soyad",
    "common.contact.email": "E-poçt",
    "common.contact.message": "Layihəniz haqqında qısa xülasə",
    "common.contact.success": "Sorğunuzu aldıq. Tezliklə geri dönüş edəcəyik.",
    "common.proof": "Seçilmiş referanslar",
    "common.detail": "Ətraflı baxış",
    "common.process": "Proses",
    "common.more": "Davamı",
    "urunler.title": "SoftenWise | Məhsullar",
    "urunler.desc": "SoftenWise Clinic, Otomini, SoftenWise Maps və BLOC — SoftenWise məhsul portfeli.",
    "urunler.brand": "SoftenWise",
    "urunler.h1": "Məhsullar",
    "urunler.lead": 'Klinikadan xəritəyə və mobilə: məhsullarımızı burada topladıq. Fərdi proqram və ya inteqrasiya üçün <a href="index.html#solutions">xidmətlərimizə</a> baxın.',
    "urunler.cta1": "Məhsullara baxın",
    "urunler.cta2": "Görüş sorğusu",
    "urunler.featured": "Öne çıxanlar",
    "urunler.jump": "Məhsul detallarına keç",
    "urunler.clinic.desc": "Görüşdən maliyyəyə klinik prosesləri vahid paneldə idarə edin.",
    "urunler.clinic.cta": "Texniki detalları nəzərdən keçirin",
    "urunler.otomini.desc": "İkinci əl qiymətləndirmə, ekspertiza və qalereya vitrini.",
    "urunler.otomini.cta": "Texniki detalları nəzərdən keçirin",
    "urunler.maps.desc": "Sahə əməliyyatları üçün korporativ CBS: xəritə, zona, marşrut və REST API.",
    "urunler.maps.cta": "Xülasə və keçidlər",
    "urunler.bloc.badge": "Mobil tətbiq",
    "urunler.bloc.desc": "İcma və sosial axın yönümlü iOS / Android tətbiqi.",
    "urunler.bloc.cta": "Tətbiq xülasəsi",
    "urunler.kicker.portfolio": "Portfel",
    "urunler.kicker.eco": "SoftenWise ekosistemi",
    "urunler.visit": "Məhsul saytına keçin",
    "urunler.clinic.lead": "Görüş və pasiyent izləmədən maliyyə və hesabata qədər klinik prosesləri mərkəzləşdirən veb panel.",
    "urunler.clinic.b1": "<strong>11 dil</strong> və çoxölkəli infrastruktur; filial görünürlüyü",
    "urunler.clinic.b2": "Pasiyent və ziyarət, görüş, maliyyə və hesabat modulları",
    "urunler.clinic.b3": "Rol əsaslı giriş və izləniləbilənlik üçün <strong>audit jurnalı</strong>",
    "urunler.clinic.b4": "Veb panel; SaaS və ya müştəri buludu seçimləri",
    "urunler.clinic.b5": "<strong>15 gün pulsuz sınaq</strong> — softenwiseclinic.com",
    "urunler.clinic.b6": "Poliklinikalar, özəl tibb mərkəzləri və çoxfiliallı strukturlar üçün",
    "urunler.otomini.lead": "Etibar yönümlü ikinci əl avtomobil ticarəti: ani rəqəmsal qiymətləndirmə, şəffaf ekspertiza və peşəkar qalereya.",
    "urunler.otomini.b1": "<strong>Ağıllı qiymətləndirmə:</strong> marka, model və təchizatla saniyələr içində ilkin dəyər",
    "urunler.otomini.b2": "<strong>Şəffaf ekspertiza:</strong> zədə və tarixçə xülasəsi",
    "urunler.otomini.b3": "<strong>Elan idarəetməsi:</strong> Otomini vitrinində qalereya yönümlü təqdimat",
    "urunler.otomini.b4": "İkinci əl salonlar, diler şəbəkələri və alqı-satqı komandaları üçün",
    "urunler.otomini.b5": "SoftenWise mühəndisliyi ilə hazırlanmış müstəqil məhsul brendi",
    "urunler.maps.lead": "Sahə əməliyyatlarını vahid paneldən izləyən korporativ <strong>CBS</strong> ekosistemi: xəritə, zona, marşrut, hesabat və REST API.",
    "urunler.maps.b1": "<strong>Vahid panel:</strong> xəritə, qat ağacı, çəkmə alətləri; ünvan / koordinat ilə canlı fokus",
    "urunler.maps.b2": "Təhlükəsiz və qadağan zonalar (poliqon); versiyalı dəyişiklik tarixçəsi",
    "urunler.maps.b3": "Geokod, marşrut, məsafə matrisi; GeoJSON / KML və <strong>REST API</strong> inteqrasiyası",
    "urunler.maps.b4": "XYZ plitələr, Nominatim, WMS / WMTS; Google Maps Platform və ya daxili xəritə xidmətləri",
    "urunler.maps.b5": "Çox icarəçi memarlıq, rol əsaslı giriş; OpenAPI / Redoc sənədləşməsi",
    "urunler.maps.b6": "Sahə, logistika və ərazi planlaması üçün",
    "urunler.bloc.lead": "İcma və sosial axın yönümlü <strong>iOS və Android</strong> mobil tətbiq — paylaşım, kəşf və qarşılıqlı əlaqə bir məhsulda.",
    "urunler.bloc.b1": "App Store və Google Play üzərindən paylama",
    "urunler.bloc.b2": "Sosial axın və icma qarşılıqlı əlaqəsinə uyğun interfeys",
    "urunler.bloc.b3": "SoftenWise mühəndislik standartları ilə hazırlanıb",
    "urunler.bloc.b4": "Mağaza-öncəli məhsul həyat dövrü",
    "urunler.bloc.b5": "iOS və Android üçün native təcrübə",
    "svc.custom.brand": "Proqram təminatı",
    "svc.custom.h1": "Fərdi proqram təminatı",
    "svc.custom.lead": "Standart paketlərin hüdudlarını aşan, prosesləri sadələşdirən və biznesinizlə böyüyən modular platformalar qururuq.",
    "svc.custom.title": "SoftenWise | Fərdi proqram təminatı",
    "svc.mobile.brand": "Mobil inkişaf",
    "svc.mobile.h1": "Mobil inkişaf",
    "svc.mobile.lead": "iOS və Android üçün məhsul yönümlü native və hybrid tətbiqlər — mağaza nəşrindən canlı izləməyə qədər.",
    "svc.mobile.title": "SoftenWise | Mobil inkişaf",
    "svc.integ.brand": "İnteqrasiya və avtomatlaşdırma",
    "svc.integ.h1": "İnteqrasiya və avtomatlaşdırma",
    "svc.integ.lead": "Dağınıq sistemləri birləşdirib məlumat axınını avtomatlaşdırırıq — əl səhvini azaldıb komandanı azad edirik.",
    "svc.integ.title": "SoftenWise | İnteqrasiya və avtomatlaşdırma",
    "svc.sec.brand": "Təhlükəsizlik və audit",
    "svc.sec.h1": "Təhlükəsizlik və audit",
    "svc.sec.lead": "Sistemlərinizi kiber təhdidlərə qarşı gücləndirir, uyğunluq və texniki auditdə yanınızda oluruq.",
    "svc.sec.title": "SoftenWise | Təhlükəsizlik və audit",
    "svc.consult.brand": "Texniki məsləhət",
    "svc.consult.h1": "Texniki məsləhət",
    "svc.consult.lead": "Memarlıq, refactor və miqyas üzrə aydın məsləhət — lazımsız texniki borc olmadan böyümək üçün.",
    "svc.consult.title": "SoftenWise | Texniki məsləhət",
    "academy.brand": "SoftenWise Academy",
    "academy.h1": "Mühəndislik intizamını birlikdə gücləndirək",
    "academy.lead": "SoftenWise Academy yalnız kod yazmağı deyil, mühəndislik intizamını və miqyaslana bilən memarlığı mərkəzə alır.",
    "academy.title": "SoftenWise | Academy",
    "career.brand": "SoftenWise Karyera",
    "career.h1": "Real məhsullar, yüksək trafik, ölçülə bilən inkişaf",
    "career.lead": "SoftenWise-də yüksək trafikli sistemlərin memarlıq qərarlarında məsuliyyət götürür, performans məsələlərini real layihələrdə həll edirsiniz.",
    "career.title": "SoftenWise | Karyera",
    "partner.brand": "Vençur tərəfdaşlığı",
    "partner.h1": "İdeyalarınızı texniki gücümüzlə böyüdək",
    "partner.lead": "Yüksək potensiallı vizyonları texniki doğrulama, MVP və böyümə strategiyası ilə dayanıqlı modellərə çeviririk.",
    "partner.title": "SoftenWise | Vençur tərəfdaşlığı",
    "resources.brand": "Resurs mərkəzi",
    "resources.h1": "Proqram qərarları üçün aydın bələdçilər",
    "resources.lead": "Qərarverənlərin real suallarına yönəlmiş məzmun — seçim, dəyər və proses.",
    "resources.title": "SoftenWise | Resurslar",
    "guide.firm.brand": "Bələdçi",
    "guide.firm.h1": "Proqram tərəfdaşı necə seçilir?",
    "guide.firm.lead": "Düzgün texnologiya tərəfdaşı layihənin nəticəsini müəyyən edir. Təklifdən texniki keyfiyyətə kritik yoxlama nöqtələrini topladıq.",
    "guide.firm.title": "SoftenWise | Proqram tərəfdaşı seçimi",
    "guide.cost.brand": "Dəyər bələdçisi",
    "guide.cost.h1": "Fərdi proqram dəyəri necə hesablanır?",
    "guide.cost.lead": "Əhatə analizi, büdcə planı və şəffaf təslim üçün praktiki çərçivə.",
    "guide.cost.title": "SoftenWise | Fərdi proqram dəyəri",
    "guide.mobile.brand": "Mobil bələdçi",
    "guide.mobile.h1": "Mobil tətbiq inkişaf prosesi",
    "guide.mobile.lead": "Uğurlu mobil məhsullar kəşf, test və nəşr intizamı ilə yaranır — yalnız kodla yox.",
    "guide.mobile.title": "SoftenWise | Mobil tətbiq prosesi",
    "err404.brand": "SoftenWise",
    "err404.h1": "404 — Səhifə tapılmadı",
    "err404.lead": "Bu ünvan artıq olmaya və ya səhv yazılmış ola bilər. Ana səhifə, xidmətlər və ya resurslardan davam edin.",
    "err404.title": "SoftenWise | Səhifə tapılmadı",
    "err404.home": "Ana səhifəyə qayıt",
}


def main() -> None:
    raw = LOCALES.read_text(encoding="utf-8")
    data = json.loads(raw.split("=", 1)[1].strip().rstrip(";"))
    page_keys = [
        k
        for k in data["tr"]
        if k.startswith(
            (
                "urunler.",
                "svc.",
                "academy.",
                "career.",
                "partner.",
                "resources.",
                "guide.",
                "err404.",
                "common.",
            )
        )
    ]
    packs = {
        "de": DE,
        "fr": FR,
        "es": ES,
        "it": IT,
        "nl": NL,
        "pt": PT,
        "ru": RU,
        "ar": AR,
        "az": AZ,
    }
    for lang, pack in packs.items():
        missing = [k for k in page_keys if k not in pack]
        if missing:
            raise SystemExit(f"{lang} missing {len(missing)}: {missing[:8]}")
        data[lang].update(pack)
        # ensure not accidentally identical to EN for sample keys
    LOCALES.write_text(
        "/* SoftenWise locales — 11 languages full page packs */\n"
        f"window.SW_LOCALES = {json.dumps(data, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
        newline="\n",
    )
    # verify
    for lang in packs:
        same = sum(1 for k in page_keys if data[lang].get(k) == data["en"].get(k))
        print(f"{lang}: same_as_en={same}/{len(page_keys)}")
    # bump script versions
    for p in ROOT.glob("*.html"):
        t = p.read_text(encoding="utf-8")
        t2 = re.sub(r"js/locales\.js\?v=\d+", "js/locales.js?v=202607174", t)
        t2 = re.sub(r"js/i18n\.js\?v=\d+", "js/i18n.js?v=202607174", t2)
        if t2 != t:
            p.write_text(t2, encoding="utf-8", newline="\n")
    print("done", len(page_keys), "page keys")


if __name__ == "__main__":
    main()
